<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
  <head
    <base href="<?php echo $this->baseUrl()?>" />
    <?php $this->headTitle('Kuukse elfkroegetocht') ?>
    <?php echo $this->headMeta() ?>
    <?php echo $this->headTitle()?>
    <?php echo $this->headStyle()?>
    <?php echo $this->headLink()?>
  </head>
  <body>
    Content:<br />
    <?php echo $this->content ?>
    <?php echo $this->headScript()?>
  </body>
</html>  