<h2>
  <a href="<?php echo $this->url(array('module' => 'scheduler', 'controller' => 'tournament', 'action' => 'index')) ?>">Toernooien</a>
  &raquo; <a href="<?php echo $this->url(array('module' => 'scheduler', 'controller' => 'tournament', 'action' => 'read', 'id' => $this->tournament->id)) ?>"><?php echo $this->escape($this->tournament->name)?></a>
  &raquo; volgende fase
</h2>

<h2>Beslissingen (strafschoppen?)</h2>
<?php if (isset($this->decisions) && $this->decisions->count() > 0): ?>
<?php echo nl2br($this->decisions) ?>
<?php else: ?>
geen
<?php endif ?>
<br /><br />

<table>
  <tr>
    <td style="vertical-align: top">
    <?php foreach ($this->groups as $group): ?>
    <?php echo $this->partial('standing/_table.phtml', array('standings' => $group->standings, 'caption' => $group->name)) ?>
    <br />
    <?php endforeach ?>
    </td>
    <td style="vertical-align: top">
      <?php foreach ($this->newGroups as $index => $newGroup): ?>
      <table border="1">
        <tr>
          <th>Nieuwe group <?php echo $index+1 ?></th>
        </tr>
        <tr>
          <th>Team</th>
        </tr>
        <?php foreach ($newGroup->tickets as $ticket): ?>
        <tr>
          <td>
            <?php echo $this->ticket($ticket)->toString(); ?>
          </td>
        </tr>
        <?php endforeach ?>
      </table>
      <br/>
      <?php endforeach ?>
    </td>
  </tr>
</table>