<?php $this->subtitle('Toernooien', $this->url(array('module' => 'scheduler', 'controller' => 'tournament', 'action' => 'index'))) ?>
<?php $this->subtitle($this->tournament->name, $this->url(array('controller' => 'tournament', 'action' => 'read', 'id' => $this->tournament->id))) ?>
<?php $this->subtitle('Volgende fase') ?>

<h3>Beslissingen</h3>
<div class="section">
  <?php if (isset($this->decisions) && $this->decisions->count() > 0): ?>
  <?php echo nl2br($this->decisions) ?>
  <?php else: ?>
  geen
  <?php endif ?>
</div>

<h3>Standen</h3>
<div class="section">
  <div style="overflow: auto">
    <?php foreach ($this->groups as $group): ?>
    <div style="float: left; margin: 0 10px 10px 0">
      <?php echo $this->partial('standing/_table.phtml', array('standings' => $group->standings, 'caption' => $group->name)) ?>
    </div>
    <?php endforeach ?>
  </div>
</div>

<h3>Nieuwe poules</h3>
<div class="section">
  <div style="overflow: auto">
    <?php foreach ($this->newGroups as $index => $newGroup): ?>
    <div style="float: left; margin: 0 10px 10px 0">
      <table>
        <tr>
          <th class="caption">Nieuwe group <?php echo $index+1 ?></th>
        </tr>
        <tr>
          <th>Team</th>
        </tr>
        <?php foreach ($newGroup->tickets as $ticket): ?>
        <tr>
          <td>
            <?php echo $this->ticket($ticket)->toString(); ?>
          </td>
        </tr>
        <?php endforeach ?>
      </table>
    </div>
    <?php endforeach ?>
  </div>
</div>