<?php $this->subtitle('Toernooien', $this->url(array('module' => 'scheduler', 'controller' => 'tournament', 'action' => 'index'))) ?>
<?php $this->subtitle($this->tournament->name) ?>

<h3>Eigenschappen</h3>
<div class="section">
  <table class="properties">
    <tr>
      <td class="name">Naam</td>
      <td class="value"><?php echo $this->escape($this->tournament->name)?></td>
    </tr>
    <tr>
      <td class="name">Start</td>
      <td class="value"><?php echo $this->locale()->getFormatter()->formatDateTime($this->tournament->starts_at, 'full-short') ?></td>
    </tr>
    <tr>
      <td class="name">Velden</td>
      <td class="value"><?php $fieldNames = array(); foreach ($this->fields as $field) {$fieldNames[] = $this->escape($field->name);} ?><?php echo implode(', ', $fieldNames) ?></td>
    </tr>
    <tr>
      <td class="name">Wedstrijdduur</td>
      <td class="value"><?php echo $this->tournament->match_duration ?> mins</td>
    </tr>
    <tr>
      <td class="name">Tussenduur</td>
      <td class="value"><?php echo $this->tournament->between_duration ?> mins</td>
    </tr>
    <tr>
      <td class="name">Toon op dashboard</td>
      <td class="value"><?php if ($this->tournament->show_in_dashboard): ?>ja<?php else: ?>nee<?php endif ?></td>
    </tr>
  </table>
  <br />
  <form class="admin-button" method="get" action="<?php echo $this->url(array('action' => 'update')) ?>">
    <input type="hidden" name="id" value="<?php echo $this->tournament->id?>" />
    <button type="submit">Wijzig <img src="ats2015/general/images/icons/16x16/edit.png" style="vertical-align: middle" /></button>
  </form>
  
  <form class="admin-button" method="get" action="<?php echo $this->url(array('controller' => 'tournament', 'action' => 'nextphase')) ?>">
    <input type="hidden" name="id" value="<?php echo $this->tournament->id?>" />
    <button type="submit">Volgende fase</button>
  </form>
</div>

<h3>Poules</h3>
<div class="section">
<table>
  <tr>
    <th style="width: 400px">Naam</th>
    <th></th>
  </tr>
  <?php foreach ($this->groups as $group): ?>
  <tr>
    <td><a href="<?php echo $this->url(array('controller' => 'group', 'action' => 'read', 'id' => $group->id)) ?>"><?php echo $this->escape($group->name)?></a></td>
    <td>
      <a href="<?php echo $this->url(array('controller' => 'group', 'action' => 'move', 'id' => $group->id, 'count' => -1)) ?>"><img src="ats2015/general/images/icons/16x16/arrow_up_blue.png" /></a> 
      <a href="<?php echo $this->url(array('controller' => 'group', 'action' => 'move', 'id' => $group->id, 'count' => 1)) ?>"><img src="ats2015/general/images/icons/16x16/arrow_down_green.png" /></a>
    </td>
  </tr>
  <?php endforeach ?>
</table>
</div>

<h3>Wedstrijden</h3>
<div class="section">
  <?php echo $this->partial('match/_table.phtml', array('matches' => $this->matches, 'hideTournaments' => true, 'showEdits' => true )) ?>
  <br />
  <form method="get" action="<?php echo $this->url(array('controller' => 'tournament', 'action' => 'generateschedule')) ?>">
    <input type="hidden" name="id" value="<?php echo $this->tournament->id?>" />
    <button type="submit">(Her)genereer wedstrijden</button>
  </form>
</div>