<h2>
  <a href="<?php echo $this->url(array('module' => 'scheduler', 'controller' => 'tournament', 'action' => 'index')) ?>">Toernooien</a>
  &raquo; <?php echo $this->escape($this->tournament->name)?>
</h2>

<b>Velden</b>: <?php $fieldNames = array(); foreach ($this->fields as $field) {$fieldNames[] = $this->escape($field->name);} ?><?php echo implode(', ', $fieldNames) ?><br />
<b>Datum</b>: <?php echo $this->locale()->getFormatter()->formatDateTime($this->tournament->starts_at, 'full-short') ?><br />
<b>Wedstrijd duur</b>: <?php echo $this->tournament->match_duration ?> mins<br />
<b>Tussen duur</b>: <?php echo $this->tournament->between_duration ?> mins<br />
<form method="get" action="<?php echo $this->url(array('controller' => 'tournament', 'action' => 'nextphase')) ?>">
  <input type="hidden" name="id" value="<?php echo $this->tournament->id?>" />
  <input type="submit" value="Volgende fase" />
</form>

<br />
<b>Poules:</b>
<table>
  <tr>
    <th>Naam</th>
    <th></th>
  </tr>
  <?php foreach ($this->groups as $group): ?>
  <tr>
    <td><a href="<?php echo $this->url(array('controller' => 'group', 'action' => 'read', 'id' => $group->id)) ?>"><?php echo $this->escape($group->name)?></a></td>
    <td>
      <a href="<?php echo $this->url(array('controller' => 'group', 'action' => 'move', 'id' => $group->id, 'count' => -1)) ?>"><img src="ats2015/general/images/icons/16x16/arrow_up_blue.png" /></a> 
      <a href="<?php echo $this->url(array('controller' => 'group', 'action' => 'move', 'id' => $group->id, 'count' => 1)) ?>"><img src="ats2015/general/images/icons/16x16/arrow_down_green.png" /></a>
    </td>
  </tr>
  <?php endforeach ?>
</table>

<br />
<b>Wedstrijden</b>:
<table>
  <tr>
    <th>Tijd</th>
    <th>Veld</th>
    <th>Poule</th>
    <th>Thuis</th>
    <th></th>
    <th>Uit</th>
    <th colspan="3">Uitslag</th>
    <th></th>
  </tr>
  <?php foreach ($this->matches as $match): ?>
  <tr>
    <td style="text-align: right"><?php echo $this->locale()->getFormatter()->formatTime($match->starts_at, 'short', "Y-m-d H:i:s") ?></td>
    <td style="padding: 0 10px 0 10px"><?php echo $this->escape($match->field->name) ?></td>
    <td style="padding: 0 10px 0 10px"><a href="<?php echo $this->url(array('controller' => 'group', 'action' => 'read', 'id' => $match->group->id)) ?>"><?php echo $this->escape($match->group->name) ?></a></td>
    <td style="padding: 0 10px 0 10px"><a href="<?php echo $this->url(array('controller' => 'team', 'action' => 'read', 'id' => $match->home_team_id)) ?>"><?php echo $this->escape($match->home_team->name) ?></a></td>
    <td>-</td>
    <td style="padding: 0 10px 0 10px"><a href="<?php echo $this->url(array('controller' => 'team', 'action' => 'read', 'id' => $match->away_team_id)) ?>"><?php echo $this->escape($match->away_team->name) ?></a></td>
    <td><?php echo $match->goals_home ?></td>
    <td>-</td>
    <td><?php echo $match->goals_away ?></td>
    <td><a href="<?php echo $this->url(array('controller' => 'match', 'action' => 'update', 'id' => $match->id)) ?>"><img src="ats2015/general/images/icons/16x16/edit.png" /></a></td>
  </tr>
  <?php endforeach ?>
</table>
  
<form method="get" action="<?php echo $this->url(array('controller' => 'tournament', 'action' => 'generateschedule')) ?>">
  <input type="hidden" name="id" value="<?php echo $this->tournament->id?>" />
  <input type="submit" value="(Her)genereer wedstrijden" />
</form>