<form method="post" action="<?php echo $this->url(array('action' => $this->action))?>">
  
  <?php if ($this->action == 'update'): ?>
  <input type="hidden" name="id" value="<?php echo $this->match->id ?>" />
  <dl>
    <dt><label for="id">#</label></dt>
    <dd><?php echo $this->match->id ?></dd>
  </dl>
  <?php endif ?>
  
  <?php if (isset($this->form['returnUrl'])): ?>
  <input type="hidden" name="form[returnUrl]" value="<?php echo $this->escape($this->form['returnUrl']) ?>" />
  <?php endif ?>
  
  <dl>
    <dt><label for="starts_at">Start</label></dt>
    <dd>
      <?php echo $this->error($this->form, 'starts_at')?>
      <?php echo $this->widget('keithwood:datetimeentry', array('name' => 'form[starts_at]', 'value' => \DateTime::createFromFormat('Y-m-d H:i:s', $this->form['starts_at']), 'config' => array('phpDatetimeFormat' => 'Y-m-d H:i:s'))) ?>
    </dd>
  </dl>
  
  <dl>
    <dt><label for="field_id">Veld</label></dt>
    <dd>
      <?php echo $this->widget('Select', array(
        'id' => 'field_id',
        'name' => 'form[field_id]',
        'value' => $this->form['field_id'],
        'options' => $this->form->getConfig('availableFields')
      )) ?>
    </dd>
  </dl>
  
  <dl>
    <dt><label for="group">Poule</label></dt>
    <dd><?php echo $this->escape($this->match->group->name)?></dd>
  </dl>
  
  <dl>
    <dt><label for="goals_home"><?php echo $this->escape($this->match->home_team->name) ?></label></dt>
    <dd>
      <?php echo $this->error($this->form, 'goals_home')?>
      <input type="text" name="form[goals_home]" id="goals_home" value="<?php echo $this->escape($this->form['goals_home'])?>" />
    </dd>
  </dl>
  
  <dl>
    <dt><label for="goals_away"><?php echo $this->escape($this->match->away_team->name) ?></label></dt>
    <dd>
      <?php echo $this->error($this->form, 'goals_away')?>
      <input type="text" name="form[goals_away]" id="goals_away" value="<?php echo $this->escape($this->form['goals_away'])?>" />
    </dd>
  </dl>
  
  
  
  <dl>
    <dd>
      <button type="submit">Opslaan</button>
    </dd>
  </dl>
</form>