<h2>Velden</h2>

<b>Teams:</b>
<table>
  <tr>
    <th>Naam</th>
    <th>Veldtype</th>
  </tr>
  <?php foreach ($this->fields as $field): ?>
  <tr>
    <td><?php echo $this->escape($field->name) ?></a></td>
    <td style="padding: 0 10px 0 10px"><?php echo $this->escape($field->field_type) ?></td>
    <td>
      <a href="<?php echo $this->url(array('action' => 'move', 'id' => $field->id, 'count' => -1)) ?>"><img src="ats2015/general/images/icons/16x16/arrow_up_blue.png" /></a> 
      <a href="<?php echo $this->url(array('action' => 'move', 'id' => $field->id, 'count' => 1)) ?>"><img src="ats2015/general/images/icons/16x16/arrow_down_green.png" /></a>
    </td>
  </tr>
  <?php endforeach ?>
</table>
