<?php $this->subtitle('Toernooien', $this->url(array('module' => 'scheduler', 'controller' => 'tournament', 'action' => 'index'))) ?>
<?php $this->subtitle($this->tournament->name, $this->url(array('controller' => 'tournament', 'action' => 'read', 'id' => $this->tournament->id))) ?>
<?php $this->subtitle('Poules') ?>
<?php $this->subtitle('toevoegen') ?>

<div class="section">
  <?php echo $this->partial('group/_modify.phtml', array('action' => 'create')) ?>
</div>