<h2>
  <a href="<?php echo $this->url(array('module' => 'scheduler', 'controller' => 'tournament', 'action' => 'index')) ?>">Toernooien</a>
  &raquo; <a href="<?php echo $this->url(array('controller' => 'tournament', 'action' => 'read', 'id' => $this->tournament->id)) ?>"><?php echo $this->escape($this->tournament->name) ?></a>
  &raquo; <?php echo $this->escape($this->group->name) ?>
</h2>
<b>Teams:</b>
<table>
  <tr>
    <th>Naam</th>
    <th></th>
  </tr>
  <?php foreach ($this->teams as $team): ?>
  <tr>
    <td><a href="<?php echo $this->url(array('controller' => 'team', 'action' => 'read', 'id' => $team->id)) ?>"><?php echo $this->escape($team->name) ?></a></td>
    <td>
      <a href="<?php echo $this->url(array('controller' => 'groupteam', 'action' => 'move', 'id' => $team->group_teams[0]->id, 'count' => -1)) ?>"><img src="ats2015/general/images/icons/16x16/arrow_up_blue.png" /></a> 
      <a href="<?php echo $this->url(array('controller' => 'groupteam', 'action' => 'move', 'id' => $team->group_teams[0]->id, 'count' => 1)) ?>"><img src="ats2015/general/images/icons/16x16/arrow_down_green.png" /></a>
    </td>
  </tr>
  <?php endforeach ?>
</table>

<br />
<b>Stand:</b>
<table border="1px solid #000">
  <tr>
    <th></th>
    <th>Team</th>
    <th>G</th>
    <th>W</th>
    <th>G</th>
    <th>V</th>
    <th></th>
    <th>DV</th>
    <th>DT</th>
    <th>DV</th>
    <th></th>
    <th>P</th>
  </tr>
  <?php foreach ($this->standings as $standing): ?>
  <tr>
    <td><?php echo $standing->getPosition() ?>.</td>
    <td><a href="<?php echo $this->url(array('controller' => 'team', 'action' => 'read', 'id' => $standing->team->id)) ?>"><?php echo $this->escape($standing->team->name) ?></a></td>
    <td><?php echo $standing->getPlayed() ?></td>
    <td><?php echo $standing->won ?></td>
    <td><?php echo $standing->drawn ?></td>
    <td><?php echo $standing->lost ?></td>
    <td></td>
    <td><?php echo $standing->goals_for ?></td>
    <td><?php echo $standing->goals_against ?></td>
    <td><?php echo $standing->getGoalsDifference() ?></td>
    <td></td>
    <td><?php echo $standing->getPoints() ?></td>
  </tr>
  <?php endforeach ?>
</table>

<br />
<b>Wedstrijden</b>:
<table>
  <tr>
    <th>Tijd</th>
    <th>Veld</th>
    <th>Thuis</th>
    <th></th>
    <th>Uit</th>
    <th colspan="3">Uitslag</th>
  </tr>
  <?php foreach ($this->matches as $match): ?>
  <tr>
    <td style="text-align: right"><?php echo $this->locale()->getFormatter()->formatTime($match->starts_at, 'short', "Y-m-d H:i:s") ?></td>
    <td style="padding: 0 10px 0 10px"><?php echo $this->escape($match->field->name) ?></td>
    <td style="padding: 0 10px 0 10px"><a href="<?php echo $this->url(array('controller' => 'team', 'action' => 'read', 'id' => $match->home_team_id)) ?>"><?php echo $this->escape($match->home_team->name) ?></a></td>
    <td>-</td>
    <td style="padding: 0 10px 0 10px"><a href="<?php echo $this->url(array('controller' => 'team', 'action' => 'read', 'id' => $match->away_team_id)) ?>"><?php echo $this->escape($match->away_team->name) ?></a></td>
    
    <td><?php echo $match->goals_home ?></td>
    <td>-</td>
    <td><?php echo $match->goals_away ?></td>
  </tr>
  <?php endforeach ?>
</table>